# Name of loaded config, to show to user
name = "System settings and drivers"

# Default argument values
# Overwrite these from the command line
default_bsd = "no"
default_bsdfs = "exfat"
default_dvd = "no"
#default_ata0 = "mass:mydrive0.bin"
#default_ata0id = "mass:mydrive0_id.bin"
#default_ata1 = "mass:mydrive1.bin"
#default_mc0 = "mass:mymc0.bin"
#default_mc1 = "mass:mymc1.bin"
default_elf = "auto"
#default_mt = "dvd"
#default_gc = "12"
#default_cfg = ""
default_dbc = false
default_logo = false

# Select the number of sectors for the FS buffer
# A small value can increase game compatibility
# A large value can increase performce
# Min=2, Max=128, Default=8
cdvdman_fs_sectors = 8

# Override the 8-byte string returned by:
# - sceCdRI
# This string is also used by:
# - sceCdReadGUID
# - sceCdReadModelID
#
# This string is used (for instance) by the sony network configuration
# to verify if the config belongs to the specific console.
#
#ilink_id = [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]

# Use the 5-byte string returned by:
# - sceCdReadDiskID
#disk_id = [0x00, 0x00, 0x00, 0x00, 0x00]

# Modules to load in emulation environment
[[module]]
file = "eesync.irx"
ioprp = "EESYNC"
env = ["EE"]
[[module]]
file = "imgdrv.irx"
env = ["EE"]
[[module]]
file = "fakemod.irx"
env = ["EE"]
